server:
  port: 8080

spring:
  application:
    name: uber

  datasource:
    url: jdbc:postgresql://82.112.237.166:5433/b2camp_db
    username: b2camp
    password: b2camp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
